### ISSUE TITLE
error on PfpParse

### ISSUE THREAD

**Issue by jjkakakk** [d0c-s4vage/pfp-vim#4]
Each time i run PfpParse inside vim, i get:

```
"__PFP_HEX__ /Users/bob/blah/classes.dex"  --No lines in buffer--
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 272, in pfp_parse
AttributeError: number
Press ENTER or type command to continue
```

on any file.

~/.pfp exists

```
~ $ cat .pfp
{"template_dirs": ["/Users/blah/path/mac/010_Editor/templates"]}
```

ls /Users/blah/path/mac/010_Editor/templates:

```
<snip> lots of .bt files
```

python --version

```
Python 2.7.10
```

can import pfp okay:

```
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pfp
>>>
```

$ pip show pfp

```
Name: pfp
Version: 0.1.14
Location: /Library/Python/2.7/site-packages
Requires: py010parser, six, intervaltree
```

checking python reqs

```
pip install --upgrade six
Requirement already up-to-date: six in /Library/Python/2.7/site-packages
Cleaning up...

~ $ pip install --upgrade intervaltree
Requirement already up-to-date: intervaltree in /Library/Python/2.7/site-packages
Requirement already up-to-date: sortedcontainers in /Library/Python/2.7/site-packages (from intervaltree)
Cleaning up...

~ $ pip install --upgrade py010parser
Requirement already up-to-date: py010parser in /Library/Python/2.7/site-packages
Cleaning up...
```

using console macvim install, 
vim --version

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jul  9 2015 23:58:42)
```

with janus, and git cloned bundle:

```
ls .janus/pfp-vim/
plugin  syntax  LICENSE  README.md
```

cheers

**Comment by d0c-s4vage** [comment]
This is due to a problem within pfp itself (https://github.com/d0c-s4vage/pfp/issues/14). pfp isn't yet 1-to-1 with 010 editor. It's slowly getting there though.

Closing here since d0c-s4vage/pfp#14 is already tracking Dex parsing in pfp
